// Generated by CoffeeScript 1.4.0
(function() {

  define(['SessionSVC'], function() {
    return function(options) {
      return [
        '$q', '$state', 'Session', function($q, $state, Session) {
          var deferred;
          deferred = $q.defer();
          Session.load().then(function(session) {
            if (options.reqAuth) {
              if (!(session != null) || !Object.getOwnPropertyNames(session).length) {
                deferred.reject(null);
                return $state.go(options.reqAuth);
              }
            } else if (options.redirAuth) {
              if (session && Object.getOwnPropertyNames(session).length) {
                deferred.reject(null);
                return $state.go(options.redirAuth);
              }
            } else {
              return deferred.resolve(true);
            }
          });
          return deferred.promise;
        }
      ];
    };
  });

}).call(this);
